services:
  app:
    build: .
    image: car-journal-backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    container_name: car-journal
    env_file:
      - .env
    networks:
      - shared-network

networks:
  shared-network:
    external: true