services:
  app:
    build: .
    image: car-journal-backend
    expose:
      - "8080"
    restart: unless-stopped
    container_name: car-journal
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "172.28.0.0/16"
        - subnet: "fd00:dead:beef::/48"